version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: competeiq
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  vectordb:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
